name: Release

on:
  push:
    tags:
      - '*'

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code - SLV`
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: savesecrets/slv
          ref: ${{ github.ref }}
          ssh-key: ${{ secrets.SLV_REPO_READ_SSH_KEY }}
      - name: Set up Go
        uses: actions/setup-go@v5
      - name: Create goreleaser config
        run: |
          mkdir -p dist
          cp .goreleaser.yaml dist/goreleaser.yaml
          git remote set-url origin git@github.com:${{ github.repository }}.git
      - name: GoReleaser - Release SLV
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release -f dist/goreleaser.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_SSH_KEY: ${{ secrets.HOMEBREW_SSH_KEY }}